version: "3"
services:
  SeleniumPneu:
    container_name: SeleniumPneu
    image: seleniumPneu
    ports: 
        - 5522:5132

  selenium-hub:
    image: selenium/hub:3.141.59-zinc
    container_name: selenium-hub
    networks:
     - seleniumGrid
    ports:
     - "4444:4444"

  chrome:
    image: selenium/node-chrome:3.141.59-zinc
    container_name: Chrome-1
    networks:
     - seleniumGrid
    depends_on:
     - selenium-hub
    environment:
     - HUB_HOST=selenium-hub
     - HUB_PORT=4444
     - NODE_MAX_INSTANCES=2
     - NODE_MAX_SESSIONS=2

  chrome2:
    image: selenium/node-chrome:3.141.59-zinc
    container_name: Chrome-2
    networks:
     - seleniumGrid
    depends_on:
     - selenium-hub
    environment:
     - HUB_HOST=selenium-hub
     - HUB_PORT=4444
     - NODE_MAX_INSTANCES=2
     - NODE_MAX_SESSIONS=2


networks:
  sonarnet:
  seleniumGrid:

volumes:
  sonarqube_conf:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_bundled-plugins:
  postgresql:
  postgresql_data: